#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentScoreInfoManager.LinqClass
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Student_Score_Info")]
	public partial class CourseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCourse(Course instance);
    partial void UpdateCourse(Course instance);
    partial void DeleteCourse(Course instance);
    #endregion
		
		public CourseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Student_Score_InfoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CourseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CourseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CourseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CourseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Course> Course
		{
			get
			{
				return this.GetTable<Course>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Course")]
	public partial class Course : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Pro_Id;
		
		private string _Pro_Name;
		
		private int _Pro_KindId;
		
		private System.Nullable<int> _Pro_Credit;
		
		private System.Nullable<int> _Pro_Time;
		
		private System.Nullable<int> _Pro_PeopleLimit;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnPro_IdChanging(string value);
    partial void OnPro_IdChanged();
    partial void OnPro_NameChanging(string value);
    partial void OnPro_NameChanged();
    partial void OnPro_KindIdChanging(int value);
    partial void OnPro_KindIdChanged();
    partial void OnPro_CreditChanging(System.Nullable<int> value);
    partial void OnPro_CreditChanged();
    partial void OnPro_TimeChanging(System.Nullable<int> value);
    partial void OnPro_TimeChanged();
    partial void OnPro_PeopleLimitChanging(System.Nullable<int> value);
    partial void OnPro_PeopleLimitChanged();
    #endregion
		
		public Course()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Id", DbType="NVarChar(5)")]
		public string Pro_Id
		{
			get
			{
				return this._Pro_Id;
			}
			set
			{
				if ((this._Pro_Id != value))
				{
					this.OnPro_IdChanging(value);
					this.SendPropertyChanging();
					this._Pro_Id = value;
					this.SendPropertyChanged("Pro_Id");
					this.OnPro_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Name", DbType="NVarChar(30)")]
		public string Pro_Name
		{
			get
			{
				return this._Pro_Name;
			}
			set
			{
				if ((this._Pro_Name != value))
				{
					this.OnPro_NameChanging(value);
					this.SendPropertyChanging();
					this._Pro_Name = value;
					this.SendPropertyChanged("Pro_Name");
					this.OnPro_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_KindId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Pro_KindId
		{
			get
			{
				return this._Pro_KindId;
			}
			set
			{
				if ((this._Pro_KindId != value))
				{
					this.OnPro_KindIdChanging(value);
					this.SendPropertyChanging();
					this._Pro_KindId = value;
					this.SendPropertyChanged("Pro_KindId");
					this.OnPro_KindIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Credit", DbType="Int")]
		public System.Nullable<int> Pro_Credit
		{
			get
			{
				return this._Pro_Credit;
			}
			set
			{
				if ((this._Pro_Credit != value))
				{
					this.OnPro_CreditChanging(value);
					this.SendPropertyChanging();
					this._Pro_Credit = value;
					this.SendPropertyChanged("Pro_Credit");
					this.OnPro_CreditChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_Time", DbType="Int")]
		public System.Nullable<int> Pro_Time
		{
			get
			{
				return this._Pro_Time;
			}
			set
			{
				if ((this._Pro_Time != value))
				{
					this.OnPro_TimeChanging(value);
					this.SendPropertyChanging();
					this._Pro_Time = value;
					this.SendPropertyChanged("Pro_Time");
					this.OnPro_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_PeopleLimit", DbType="Int")]
		public System.Nullable<int> Pro_PeopleLimit
		{
			get
			{
				return this._Pro_PeopleLimit;
			}
			set
			{
				if ((this._Pro_PeopleLimit != value))
				{
					this.OnPro_PeopleLimitChanging(value);
					this.SendPropertyChanging();
					this._Pro_PeopleLimit = value;
					this.SendPropertyChanged("Pro_PeopleLimit");
					this.OnPro_PeopleLimitChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
